### ISSUE TITLE
/dev/tty assignment issues on UGV

### ISSUE THREAD

**Issue by arjo129** [arjo129/darpasubt#31]
UGV fails to initialize sensors to correct port. Need to setup udev rules such that when arduino appears, it appears as `/dev/arduino` or something like that. Currently rplidar is set up to be symlinked to `/dev/rplidar`

**Comment by lekoook** [comment]
Arduino Mega is assigned with /dev/arduino_mega abd RPLidar with /dev/rplidar symbolic links.
