### ISSUE TITLE
Horn slipping on servo.

### ISSUE THREAD

**Issue by arjo129** [arjo129/darpasubt#42]

**Comment by lekoook** [comment]
Metal horns purchased, waiting for arrival.

**Comment by lekoook** [comment]
Horns arrived and have tried attaching to the wheel mount. Seems to be working fine.
Will need to attach all of them and test on ground.

**Comment by lekoook** [comment]
Metal horns to be working fine at the moment, should last us for a while.
Although it should be noted that the horn's teeth are not snugged fit with the servo grooves. We should have higher quality horns in future.
